// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enrsgpyzcecvlupwjppw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVucnNncHl6Y2Vjdmx1cHdqcHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTA3MTUsImV4cCI6MjA2Mzc4NjcxNX0.PSMluY63n1ektEVfdyumgPJyd7yLUs9oUcK2bx9F8ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);